"""
Central UI theme configuration for BioForge.
"""

# Sidebar
SIDEBAR_WIDTH = 220
SIDEBAR_CORNER_RADIUS = 12

# Navigation Buttons
NAV_BUTTON_HEIGHT = 40
NAV_BUTTON_CORNER_RADIUS = 8

NAV_BUTTON_PADDING_Y = 4

ACTIVE_BUTTON_COLOR = ("gray70", "gray30")
INACTIVE_BUTTON_COLOR = ("gray25", "gray25")

# Fonts
TITLE_FONT_SIZE = 24
SUBTITLE_FONT_SIZE = 12
FOOTER_FONT_SIZE = 12

# Spacing
LOGO_PADDING_X = 15
LOGO_PADDING_Y = (20, 10)

NAVIGATION_PADDING_X = 10
NAVIGATION_PADDING_Y = 10

FOOTER_PADDING_X = 15
FOOTER_PADDING_Y = (10, 20)

# -----------------------------
# Analysis Page
# -----------------------------

LEFT_PANEL_WEIGHT = 1
RIGHT_PANEL_WEIGHT = 2

LEFT_PANEL_PADX = (10, 5)
RIGHT_PANEL_PADX = (5, 10)

PAGE_PADY = 10

SECTION_PADX = 15
SECTION_PADY = 10

SECTION_TITLE_PADX = 10
SECTION_TITLE_PADY = (10, 5)

CHECKBOX_PADX = 15
CHECKBOX_PADY = 2

ACTION_BUTTON_PADX = 15
ACTION_BUTTON_PADY = (15, 15)

RESULT_PANEL_PADX = 15
RESULT_PANEL_PADY = (0, 15)

RESULT_TITLE_PADY = (15, 10)

SECTION_TITLE_FONT_SIZE = 16
RESULT_TITLE_FONT_SIZE = 20